- name: creating Fireball init file
  template:
    src: "fireball-init.j2"
    dest: "/etc/init.d/fireball"
    owner: "root"
    group: "root"
    mode: "755"

- name: creating Fireball systemd service file
  template:
    src: "fireball.service.j2"
    dest: "/lib/systemd/system/fireball.service"
    owner: "root"
    group: "root"
    mode: "755"

- name: removing all previous configurations from /etc/fireball
  file:
    path: "/etc/fireball"
    state: "absent"

- name: creating /etc/fireball
  file:
    path: "/etc/fireball"
    state: "directory"

- name: stoppping fireball
  shell: service fireball stop
  ignore_errors: True

- name: copying Fireball binary
  gc_storage:
    bucket: "{{ fireball_releases_bucket }}"
    dest: "/usr/bin/fireball"
    gs_access_key: "{{ fireball_releases_access_key }}"
    gs_secret_key: "{{ fireball_releases_secret_key }}"
    mode: "get"
    object: "{{ fireball_releases_file }}"
    region: "NAM4"

- name: setting permissions for /usr/bin/fireball
  file:
    path: "/usr/bin/fireball"
    owner: "root"
    group: "root"
    mode: "755"

- name: setting permissions for /etc/fireball
  file:
    path: "/etc/fireball"
    state: "directory"
    recurse: "yes"
    owner: "root"
    group: "root"
    mode: "755"

- name: register Fireball as service
  systemd:
    name: "fireball"
    enabled: "yes"
    daemon_reload: "yes"
